#!/usr/bin/env bash
# my subdomains information

# Function to display information about a subdomain
display_info() {
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

# Loop through the default subdomains: www, lb-01, web-01, web-02
# If the second argument (subdomain) is provided or not, display information accordingly
for subdomain in "www" "lb-01" "web-01" "web-02"; do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ]; then
        display_info "$1" "$subdomain"
    fi
done
