#!/usr/bin/env bash
# writing a script that loops 1 to 10 having iterations in the middle using
# while loop, if, elif and else statements

count=1
while [ $count -ne 11 ]
do
    if [ $count -eq 4 ]; then
	echo "bad luck"
    elif [ $count -eq 8 ]; then
	echo "good luck"
    else
	echo "Best School"
    fi
    ((count++))
done
